neo4j:
  name: neo4j-dashboard
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "neo4j-admin"
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
