apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: service
build:
  artifacts:
    - image: localhost:32000/jqassistant-component-dashboard
      jib:
        args: [-Pproduction]
        project: org.jqassistant.tooling.dashboard:jqassistant-dashboard-service
deploy:
  helm:
    releases:
      - name: dashboard-release
        chartPath: src/main/helm/jqassistant-component-dashboard
        valuesFiles:
          - src/test/helm/microk8s/dashboard-values.yaml
