apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: service
build:
  artifacts:
    - image: localhost:32000/jqassistant-component-dashboard
      jib:
        args: [-Pproduction]
        project: org.jqassistant.tooling.dashboard:jqassistant-dashboard-service
manifests:
  rawYaml:
    - k8s/dashboard.yaml
