@startuml
folder Build {
    component Maven as maven
    component jQAssistant as jqassistant
    component "Component Dashboard Plugin" as plugin <<jQAssistant Plugin>>
    database "Plugin-Datenbank" as pluginDb <<Neo4j>>
}

folder Service {
    component Dashboard as dashboard <<Spring Boot>>
    interface API as api <<REST>>
    interface UI as ui
    dashboard .up.> api
    dashboard .up.> ui
   database "Service-Datenbank" as db <<Neo4j>>
}

folder Desktop {
    component Browser as browser
}


maven --> jqassistant : uses
jqassistant --> plugin : uses
plugin ..> api : publishes
plugin .down.> pluginDb
browser ..> ui : uses
dashboard .down.> db : uses
@enduml
